### ISSUE TITLE
Mail Account Management configuration missing after upgrade 6.0.37

### ISSUE THREAD

**Issue by ferreiramm** [Centuran/OTRS-Community-Edition#15]
Hi, 

After upgrade my OTRS instance from 6.0.29 to 6.0.37 my Mail Account Management configuration missing. 

![image](https://user-images.githubusercontent.com/118991502/203811108-8712c39e-c207-40df-96b3-d8da165e4cb2.png)

**Comment by odyniec** [comment]
Thanks for reaching out. Since investigating this issue may involve sensitive mail account data, please contact us by email at info(at)otrscommunityedition(dot)com or info(at)centuran(dot)com and we'll help you fix this.
