### ISSUE TITLE
Wide character in shmwrite at /opt/otrs/Kernel/System/Log.pm line 263

### ISSUE THREAD

**Issue by drboone** [Centuran/OTRS-Community-Edition#3]
I think this may be a perl 5.34 thing.  I was able to work around it by modifying the line to read:

`shmwrite( $Self->{IPCSHMKey}, utf8::decode($Data . $String), 0, $Self->{IPCSize} ) || die $!;`

**Comment by lucmurer** [comment]
I can confirm, that this also fixed the problem in our installation of OTRS CE 6.0.40. Before the MailAccountFetcher crashed on every Mail it would get from Microsoft365

**Comment by odyniec** [comment]
Well, late as it is, this issue has been fixed in the version released yesterday. Thank you.
