### ISSUE TITLE
6.032-httpd.service failed

### ISSUE THREAD

**Issue by tune6688** [Centuran/otrs-community-edition#4]
Dear experts
System: centos7 and  otrs-community-editon 6.032.

I perform "shell> ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/conf.d/zzz_otrs.conf" and" systemctl restart httpd"
got error message"Job for httpd.service failed. See "systemctl status httpd.service" and "journalctl -xe" for details."

Run " shell>systemctl status httpd.service -l" got "● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: protocol) since 四 2021-06-24 15:17:04 CST; 52s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 5955 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=0/SUCCESS)
  Process: 10572 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=0/SUCCESS)
 Main PID: 10572 (code=exited, status=0/SUCCESS)

6月 24 15:17:04 localhost.localdomain systemd[1]: Starting The Apache HTTP Server...
6月 24 15:17:04 localhost.localdomain httpd[10572]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
6月 24 15:17:04 localhost.localdomain httpd[10572]: httpd (pid 6759) already running
6月 24 15:17:04 localhost.localdomain systemd[1]: Failed to start The Apache HTTP Server.
6月 24 15:17:04 localhost.localdomain systemd[1]: Unit httpd.service entered failed state.
6月 24 15:17:04 localhost.localdomain systemd[1]: httpd.service failed."

As to how to solve this problem ,I have no idea.Could you give me some suggestions? Thank you !

**Comment by kgluszak** [comment]
Hello tune6688,
did you run 
/opt/otrs/bin/otrs.SetPermissions.pl and you are sure that the file "/opt/otrs/scripts/apache2-httpd.include.conf" is readable by the apache?

**Comment by tune6688** [comment]
Dear Kgluszak
Thanks for your help!
opt/otrs/bin/otrs.SetPermissions.pl ---Yes,I did it.
/opt/otrs/scripts/apache2-httpd.include.conf"---I conirmed that soft link is ready. Actually if I remove etc/httpd/conf.d /zzz_otrs.conf, 
then apache can be worked.

**Comment by kgluszak** [comment]
Hello,
I am still not over with possible file permission issue :D

Please try the following:
1. Remove the link.
2. Check if apache can be started without a problem.
3. Copy the file from /opt/otrs/scripts/apache2-httpd.include.conf directly to /etc/httpd/conf.d (so we can check if the link is an issue)
4. restart apache.

In case of error still persisting try following:
5. Paste output of:
`getenforce`
6. Hit the new file "/etc/httpd/conf.d/apache2-httpd.include.conf" with permission update 
`chmod 777` 
for testing pupouse so it can be read by anyone.
7. Check apache log (/var/log/httpd/error_log) if it says something valuable right after the apache restarting and copy/paste.
8. Do the same with: 
`journalctl -xe`
9. Check what:
`service httpd configtest `
prints - should be "Syntax OK"
10. Please print 
`httpd -v`
11. Check if any of the required apache modules is not missing:
`/opt/otrs/bin/otrs.CheckModules.pl`

Be sure to delete any sensitive data before posting here or you can email me the things I requested at 
kamil.gluszak@centuran.com and I will get back to You.

**Comment by tune6688** [comment]
Dear  kgluszak 
I tried to reinstall centos7 and otrs , it is fine now.
Thank you so much for your help again.
