### ISSUE TITLE
6.0.32 - Hidden navigation bar

### ISSUE THREAD

**Issue by dyxen** [Centuran/OTRS-Community-Edition#5]
When I logged into v6.0.32 (upgraded from v6.0.29) there is no navigation bar (Dashboard, Customers, Calendar, Ticket, Reports..). If I go to HTML Inspect mode there is style with **visibility: hidden** and if I delete hidden parameter then Navigation bar works.

`<ul id="Navigation" class="Draggable ARIARoleNavigation" style="visibility: hidden;" role="navigation">`

System: Debian 10
OTRS Version 6.0.32
Apache: Apache/2.4.38
Postgre SQL: (PostgreSQL) 9.6.22

**Comment by kgluszak** [comment]
Hello,
did you manage to fix it? If not did you run command:
`Maint::Config::Rebuild`
after the upgrade? Also if it doesn't help try `Maint::Cache::Delete` and `Maint::Loader::CacheCleanup`.
If those doesn't help let us know if you have any extensions installed regarding Navigation that might be create a conflict.

**Comment by dyxen** [comment]
Hi again,

Yes that fixed the issue. Thank you very much.
I ran the 
`Maint::Config::Rebuild`,
`Maint::Cache::Delete` and
`Maint::Loader::CacheCleanup`. This fixed the problem.
